int softdrink, milk, total;
int recievePayment;
double taxRate;
int change;
int input1;
double input2;
int sigInputMin, sigInputMax, sigOutput;
int listPrice;
long discount09, discount07, discount05, discount02, discount500;
int inputAD, heldOlympic;
int inputNo, inputMM;
int i,j;
int money = 1, month = 1, testScore;
int count;